name: Master

on: [push]
# on:
#   push:
#     branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Fetch Dependencies
        run: yarn install

      - name: Publish
        run: yarn deploy
